name: movie_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.0.0
  connectivity_plus: ^2.3.5
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/karte-dribbble.jpg
    - assets/image1.jfif
    - assets/image2.jfif
    - assets/image3.jfif
    - assets/image4.jfif
    - assets/image5.jfif
    - assets/image6.jfif
    - assets/s1.jfif
    - assets/s2.jfif
    - assets/s3.jfif
    - assets/s4.jfif
    - assets/s5.jfif
    - assets/s6.jfif
